Refactored the code.
Renamed some functions and changed some messages and comments to something more fitting.

diff --git a/chaptedit b/chaptedit
--- a/chaptedit
+++ b/chaptedit
@@ -493,7 +493,7 @@ check_file ()
 		return 1
 	fi
 
-	# Check the file extension and create backup if it's not txt
+	# Check the file extension and create backup if it's not txt, ogm or xml
 	extension="${1##*.}"
 	if [[ "${extension,,}" != "txt" ]] && [[ "${extension,,}" != "ogm" ]] && [[ "${extension,,}" != "xml" ]]; then
 		cp "$1" "$1.bak" 2> /dev/null
@@ -508,7 +508,7 @@ check_file ()
 	# We use both file and uchardet (if it is available) because no one is perfect.
 	# file doesn't get right some non-unicode encodings, but for UTF-16 is preferable
 	# than uchardet because the latter doesn't specify if it is UTF-16BE or UTF-16LE.
-	# uchardet doesn't exist for Cygwin but does for MinGW. One place you can find a binary is here:
+	# uchardet doesn't exist for Cygwin, but one place you can find a Windows binary is here:
 	# https://sourceforge.net/projects/cbadvanced/files/Repo/
 	# For chaptedit to be able to use uchardet put uchardet.exe inside /bin directory in the Cygwin installation folder.
 	# This uchardet has 2 problems: It needs windows-style path and it produces windows-style line endings.
@@ -536,7 +536,7 @@ check_file ()
 }
 
 
-read_txt ()
+read_file ()
 {
 	# Make all line endings dos-like
 	dos2unix -q "$1" 2> /dev/null
@@ -672,7 +672,7 @@ check_txt ()
 		else
 			mv "$1.bak" "$1" 2> /dev/null
 		fi
-		echo "${red}Error: \"$1\" is not a valid txt file${normal}"
+		echo "${red}Error: \"$1\" is not a valid chapters file${normal}"
 		return 1
 	elif ! [[ $backup ]]; then
 		rm -f "$1.bak" 2> /dev/null
@@ -691,9 +691,9 @@ basic_clean_up ()
 		return 1
 	fi
 
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -742,9 +742,9 @@ shift_time ()
 	fi
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -849,9 +849,9 @@ change_fps ()
 	fi
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -940,9 +940,9 @@ adjust_time ()
 	fi
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1069,9 +1069,9 @@ adjust_time_v2 ()
 	fi
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1253,9 +1253,9 @@ synchronize_with_file ()
 	fi
 
 	# Read file to synchronize to
-	read_txt "$synchronizefile"
+	read_file "$synchronizefile"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1267,6 +1267,7 @@ synchronize_with_file ()
 	if (($? != 0)); then
 		return 1
 	fi
+
 
 	if ! [[ $synchronizetimebytime ]]; then
 		# Find the first and last chapter time of the file to synchronize to
@@ -1320,9 +1321,9 @@ synchronize_with_file ()
 		fi
 
 		# Read text file to arraytxt
-		read_txt "$inputfilename"
+		read_file "$inputfilename"
 
-		# Exit this function if the return code of read_txt is not 0
+		# Exit this function if the return code of read_file is not 0
 		if (($? != 0)); then
 			return 1
 		fi
@@ -1429,9 +1430,9 @@ synchronize_with_file ()
 		fi
 
 		# Read text file to arraytxt
-		read_txt "$inputfilename"
+		read_file "$inputfilename"
 
-		# Exit this function if the return code of read_txt is not 0
+		# Exit this function if the return code of read_file is not 0
 		if (($? != 0)); then
 			return 1
 		fi
@@ -1526,9 +1527,9 @@ replace_text ()
 	IFS=$'\n'			# new field separator, the end of line
 
 	if [[ $replace3 ]]; then
-		read_txt "$inputfilename"
+		read_file "$inputfilename"
 
-		# Exit this function if the return code of read_txt is not 0
+		# Exit this function if the return code of read_file is not 0
 		if (($? != 0)); then
 			return 1
 		fi
@@ -1546,9 +1547,9 @@ replace_text ()
 		fi
 		unset temparray
 	else
-		read_txt "$inputfilename"
+		read_file "$inputfilename"
 
-		# Exit this function if the return code of read_txt is not 0
+		# Exit this function if the return code of read_file is not 0
 		if (($? != 0)); then
 			return 1
 		fi
@@ -1580,7 +1581,7 @@ replace_text ()
 }
 
 
-join_txt ()
+join_files ()
 {
 	# Check if the input file is a text
 	check_file "$jointxt"
@@ -1594,9 +1595,9 @@ join_txt ()
 	encodingjoin=$encoding
 
 	# Read text file to arraytxt
-	read_txt "$jointxt"
+	read_file "$jointxt"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1625,9 +1626,9 @@ join_txt ()
 	encodinginput=$encoding
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1764,7 +1765,7 @@ join_txt ()
 }
 
 
-split_txt ()
+split_file ()
 {
 	# Check if the input file is a text
 	check_file "$inputfilename"
@@ -1775,9 +1776,9 @@ split_txt ()
 	fi
 
 	# Read text file to arraytxt
-	read_txt "$inputfilename"
+	read_file "$inputfilename"
 
-	# Exit this function if the return code of read_txt is not 0
+	# Exit this function if the return code of read_file is not 0
 	if (($? != 0)); then
 		return 1
 	fi
@@ -1854,11 +1855,11 @@ split_txt ()
 		fi
 
 		if ((p < pa)); then
-			echo "${red}Error: Split time cannot be shorter than the first chapter time.${normal}"; return 1
+			echo "${red}Error: Split time cannot precede the first chapter time.${normal}"; return 1
 		fi
 
 		if ((p > pb)); then
-			echo "${red}Error: Split time cannot exceed the duration of the chapters file.${normal}"; return 1
+			echo "${red}Error: Split time cannot exceed the last chapter time.${normal}"; return 1
 		fi
 
 		# Find the chapter to make the split
@@ -1934,7 +1935,7 @@ split_txt ()
 		fi
 
 		if ((p < pa)); then
-			echo "${red}Error: Split time cannot be shorter than the first chapter time.${normal}"; return 1
+			echo "${red}Error: Split time cannot precede the first chapter time.${normal}"; return 1
 		fi
 
 		# Find the chapter to make the split
@@ -2105,11 +2106,11 @@ master_function ()
 	fi
 
 	if [[ $jointxt ]]; then
-		join_txt; (($? != 0)) && return 1
+		join_files; (($? != 0)) && return 1
 	fi
 
 	if [[ $splittxt ]]; then
-		split_txt; (($? != 0)) && return 1
+		split_file; (($? != 0)) && return 1
 	fi
 
 	if ! [[ $txtok ]]; then
@@ -2253,7 +2254,7 @@ if [[ $inputdirectory ]]; then
 		fi
 
 		if [[ $splittxt ]]; then
-			split_txt
+			split_file
 		fi
 
 		if ! [[ $txtok ]]; then
